apiVersion: apps/v1
kind: Deployment
metadata:
  name: serene-space
  labels:
    app: serene-app-dv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serene-app-dv
  template:
    metadata:
      labels:
        app: serene-app-dv
    spec:
      containers:
      - name: myapp
        image: abhishek7022/seabiscuit:testing-v0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "120m"
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          allowPrivilegeEscalation: true
