apiVersion: apps/v1
kind: Deployment
metadata:
  name: serene-space
  labels:
    app: serene-app-dv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serene-app-dv
  template:
    metadata:
      labels:
        app: serene-app-dv
    spec:
      containers:
      - name: myapp
        image: abhishek7022/seabiscuit:testing-v0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirstWithHostNet  # Provides better DNS behavior in some cases
