apiVersion: v1
kind: Service
metadata:
  name: serene-space-svc-dv
  labels:
    app: serene-app-dv
spec:
  selector:
    app: serene-app-dv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Targets port 80 in the container
  type: ClusterIP  # Internal communication only within the cluster (default)
