apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-space-app-prod
  namespace: serene-pr
spec:
  project: serene-space-app-prod
  source:
    repoURL: https://github.com/Abhishek7022/Argo-CD-k8s.git
    targetRevision: HEAD
    path: ./namespaces/serene/ss-prod/
  destination:
    server: https://kubernetes.default.svc
    namespace: serene-pr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
