apiVersion: apps/v1
kind: Deployment
metadata:
  name: serene-space-pr
  labels:
    app: serene-app-pr
spec:
  replicas: 3  # Increase replicas for high availability
  selector:
    matchLabels:
      app: serene-app-pr
  template:
    metadata:
      labels:
        app: serene-app-pr
    spec:
      containers:
      - name: myapp
        image: abhishek7022/seabiscuit:v1.0  # Pin to a stable version for production
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"  # Increased limits for production load
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 4566
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
      restartPolicy: Always  # Ensure the pod always restarts in production environments
