apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: serene-app-pr
    app.kubernetes.io/instance: my-space-app-prod
  name: serene-space-pr
  namespace: serene-pr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serene-app-pr
  template:
    metadata:
      labels:
        app: serene-app-pr
    spec:
      containers:
        - image: abhishek7022/seabiscuit:testing-v0
          imagePullPolicy: Always
          name: my-space-app
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
      restartPolicy: Always
