apiVersion: autoscaling/v2beta2  # HPA for automatic scaling based on resource usage
kind: HorizontalPodAutoscaler
metadata:
  name: serene-space-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serene-space-pr
  minReplicas: 2  # Minimum 2 replicas
  maxReplicas: 4  # Can scale up to 4 replicas based on load
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75  # Scale when CPU exceeds 75%