apiVersion: v1
kind: Service
metadata:
  name: serene-space-svc-pr
  labels:
    app: serene-app-pr
spec:
  selector:
    app: serene-app-pr
  ports:
    - protocol: TCP
      port: 4545
      targetPort: 4566  # Targets port 80 in the container
  type: ClusterIP  # Internal communication only within the cluster (default)
