apiVersion: v1
kind: Service
metadata:
  labels:
    app: serene-app-pr
    app.kubernetes.io/instance: my-space-app-prod
  name: serene-space-svc-pr
  namespace: serene-pr
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: serene-app-pr
  type: LoadBalancer
