apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: argocd
spec:
  project: artifactory
  source:
    repoURL: https://github.com/Abhishek7022/Argo-CD-k8s.git
    path: ./namespaces/artifactory/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: artifactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
