apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-pv
  namespace: artifactory
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/artifactory"