apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: artifactory
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      securityContext:
        fsGroup: 65534  # Use a non-root fallback group for mounted volumes
      initContainers:
        - name: init-chown
          image: docker.bintray.io/jfrog/artifactory-oss:latest  # Same image as the main container
          command: ['sh', '-c', 'chown -R $(id -u):$(id -g) /opt/jfrog/artifactory/var']
          volumeMounts:
            - name: artifactory-data
              mountPath: /opt/jfrog/artifactory/var
          securityContext:
            runAsUser: 0  # Run as root to change ownership
            runAsGroup: 0
            allowPrivilegeEscalation: false
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: artifactory-data
              mountPath: /var/opt/jfrog/artifactory
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-pvc
      restartPolicy: Always
