apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: artifactory
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      securityContext:
        fsGroup: 1030  # Ensure the mounted volumes are owned by the correct group (1030)
      initContainers:
        - name: init-chown
          image: busybox
          command: ['sh', '-c', 'chown -R 1030:1030 /opt/jfrog/artifactory/var']
          volumeMounts:
            - name: artifactory-data
              mountPath: /opt/jfrog/artifactory/var
          securityContext:
            runAsUser: 0  # Run as root to change ownership
            runAsGroup: 0
            allowPrivilegeEscalation: false
        - name: init-master-key
          image: busybox
          command: ['sh', '-c', 'if [ ! -f /opt/jfrog/artifactory/var/etc/security/keys/master.key ]; then openssl rand -base64 32 > /opt/jfrog/artifactory/var/etc/security/keys/master.key; fi']
          volumeMounts:
            - name: artifactory-data
              mountPath: /opt/jfrog/artifactory/var
          securityContext:
            runAsUser: 0  # Run as root to create the key
            runAsGroup: 0
            allowPrivilegeEscalation: false
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: artifactory-data
              mountPath: /var/opt/jfrog/artifactory
          securityContext:
            runAsUser: 1030  # Ensure Artifactory runs as the correct user (1030)
            runAsGroup: 1030
            allowPrivilegeEscalation: false  # Prevent privilege escalation
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-pvc
      restartPolicy: Always
