apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: artifactory
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      securityContext:
        runAsUser: 1030
        runAsGroup: 1030
        fsGroup: 1030  # Ensures that the mounted volume has appropriate permissions
      initContainers:
      - name: init-chown
        image: busybox
        command: ['sh', '-c', 'chown -R 1030:1030 /opt/jfrog/artifactory/var']
        volumeMounts:
        - name: artifactory-data
          mountPath: /opt/jfrog/artifactory/var
      containers:
      - name: artifactory
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: artifactory-data
            mountPath: /opt/jfrog/artifactory/var
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-pvc
