apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: artifactory
spec:
  selector:
    app: artifactory
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP