
apiVersion: v1
kind: Namespace
metadata:
  name: serene

---

apiVersion: v1
kind: Pod
metadata:
  name: serene-space
  namespace: serene
  labels:
    app: my-space-app
spec:
  containers:
  - name: serene-space
    image: abhishek7022/seabiscuit:testing-v0
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: serene-svc
  namespace: serene
spec:
  selector:
    app: my-space-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
